default: &default
  adapter: postgresql
  user: postgres_user
  password: postgres_pass
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: database
  database: postgress_db

test:
  <<: *default
  database: myrubyblog
