version: "3.7"

services:
  database:
    container_name: eam_pg_container
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  ruby_dev:
    build: .
    container_name: eam_ruby_container
    ports:
      - "3000:3000"
    volumes:
      - ./core:/home/app
    depends_on:
      - database
  
      